---
- hosts: all
  gather_facts: true
  remote_user: ec2-user
  become: true
  become_method: sudo
  vars:
    ansible_ssh_private_key_file: "{{ lookup('env', 'ANSIBLE_PRIVATE_KEY_FILE') }}"
  tasks:
    - name: Install packages
      apt:
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'cri-o', 'kubeadm', 'kubelet', 'kubectl']
        update_cache: yes
    
    - name: Copy kernel modules files for Kubernetes and CRI-O
      copy:
        content: |
          overlay
          br_netfilter
        dest: "{{ item }}" #/etc/modules-load.d/k8s.conf
        owner: root
        group: root
        mode: '0644'
      with_fileglob:
        - /etc/modules-load.d/k8s.conf
        - /etc/modules-load.d/crio.conf

    - name: Load kernel modules
      command: "{{ item }}"
      with_items:
        - modprobe overlay
        - modprobe br_netfilter

    - name: Copy sysctl parameter files for Kubernetes and CRI-O
      copy:
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward                 = 1
        dest: "{{ item }}" #/etc/sysctl.d/k8s.conf
        owner: root
        group: root
        mode: '0644'
      with_fileglob:
        - /etc/sysctl.d/k8s.conf
        - /etc/sysctl.d/99-kubernetes-cri.conf

    - name: Load sysctl parameters
      sysctl:
        name:
          - net.bridge.bridge-nf-call-iptables
          - net.bridge.bridge-nf-call-ip6tables
          - net.ipv4.ip_forward
        value: 1
        sysctl_set: yes
        state: present
