variable "output_all_ids" {
  description = "All instance IDs generated by root module"
}

variable "output_all_ips" {
  description = "All IPs generated on root module"
}

variable "output_key_name" {
  description = "Key used for accessing the instances remotely"
}